CREATE VIEW allemployee AS  
SELECT  
    '0' AS ptype, 
    '1' AS isoperator, 
    '1' AS synetcall, 
    empno AS ccode, 
    empno, 
    lastname, 
    firstname, 
    address1, 
    address2, 
    address3, 
    cityname, 
    postcode, 
    telepno1, 
    ext1, 
    telepno2, 
    ext2, 
    birthdt, 
    sex, 
    jobclass, 
    defaproj, 
    marriage, 
    id_card, 
    cardtype, 
    jobtitle, 
    deptno, 
    empstatus, 
    employdt, 
    termindt, 
    isupdate, 
    ac_need, 
    def_num1, 
    def_date1, 
    def_int1, 
    def_str1, 
    def_str2, 
    def_str3, 
    CAST(ocode AS VARCHAR) AS ocode, 
    verdtm, 
    forbid, 
    forbiddt, 
    max_borrow, 
    creditnum, 
    credit_adjust, 
    initial_num, 
    bopomofo, 
    CAST(2 AS BIGINT) AS seq  
FROM fg_other_emp  

UNION ALL  

SELECT  
    '1' AS type, 
    COALESCE(hr_epm_main.isoperator, '0') AS isoperator,
    COALESCE(hr_epm_main.synetcall, '0') AS synetcall, 
    hr_epm_main.ccode, 
    hr_epm_main.bill_no AS empno, 
    hr_epm_main.bill_name AS lastname, 
    hr_epm_main.evername AS firstname, 
    hr_epm_link.address1, 
    hr_epm_link.address2, 
    hr_epm_link.address3, 
    CAST(hr_epm_base.city AS VARCHAR) AS cityname, 
    hr_epm_link.pcode AS postcode, 
    hr_epm_link.tell1 AS telepno1, 
    hr_epm_link.ext1 AS ext1, 
    hr_epm_link.tell2 AS telepno2, 
    hr_epm_link.ext2 AS ext2, 
    hr_epm_base.birthday AS birthdt, 
    hr_epm_main.sexno AS sex, 
    CAST(hr_epm_main.jobclass AS VARCHAR) AS jobclass, 
    hr_epm_main.defaproj, 
    CAST(hr_epm_base.marriage AS VARCHAR) AS marriage, 
    hr_epm_main.cardno AS id_card, 
    CAST(hr_epm_main.cardtype AS VARCHAR) AS cardtype, 
    CAST(hr_epm_main.jobtitle AS VARCHAR) AS jobtitle, 
    CAST(hr_epm_main.phid_dept AS VARCHAR) AS deptno, 
    CAST(hr_epm_main.empstatus AS VARCHAR) AS empstatus, 
    hr_epm_main.cdt AS employdt, 
    hr_epm_main.dimissdt AS termindt, 
    hr_epm_main.isupdate, 
    hr_epm_finance.ac_need, 
    hr_epm_main.def_num1, 
    hr_epm_main.def_date1, 
    hr_epm_main.def_int1, 
    hr_epm_main.def_str1, 
    hr_epm_main.def_str2, 
    hr_epm_main.def_str3, 
    CAST(hr_epm_main.phid_org AS VARCHAR) AS ocode, 
    hr_epm_main.verdtm, 
    hr_epm_main.forbid, 
    hr_epm_main.forbiddt, 
    hr_epm_main.max_borrow, 
    hr_epm_finance.creditnum, 
    hr_epm_finance.credit_adjust, 
    hr_epm_finance.initial_num, 
    hr_epm_main.bopomofo, 
    hr_epm_main.seq  
FROM hr_epm_main  
INNER JOIN hr_epm_base ON hr_epm_main.ccode = hr_epm_base.ccode  
INNER JOIN hr_epm_link ON hr_epm_main.ccode = hr_epm_link.ccode  
INNER JOIN hr_epm_finance ON hr_epm_main.ccode = hr_epm_finance.ccode  
WHERE  
    hr_epm_base.systype = 0 AND  
    hr_epm_base.systype = hr_epm_link.systype AND  
    hr_epm_base.systype = hr_epm_finance.systype;