CREATE VIEW uv_caq_proj_record_rep AS
-- 项目质量记录视图（整合主表与历史表）
(
  SELECT 
    CAST(phid AS bigint) as phid,
    CAST(checkno AS varchar(60)) as checkno,
    CAST(wasteno AS varchar(8)) as wasteno,
    CAST(conclusion AS varchar(1)) as conclusion,
    CAST(sampleqty AS numeric) as sampleqty,
    CAST(wqty AS numeric) as wqty,
    CAST(stypeno AS varchar(30)) as stypeno,
    CAST(wbqty AS numeric) as wbqty,
    CAST(bbqty AS numeric) as bbqty,
    CAST(remarks AS varchar(255)) as remarks,
    CAST(def_int1 AS integer) as def_int1,
    CAST(def_int2 AS integer) as def_int2,
    CAST(def_str1 AS varchar(60)) as def_str1,
    CAST(def_str2 AS varchar(60)) as def_str2,
    CAST(def_str3 AS varchar(60)) as def_str3,
    CAST(def_num1 AS numeric) as def_num1,
    CAST(def_num2 AS numeric) as def_num2,
    CAST(tecrequest AS varchar(255)) as tecrequest,
    CAST(ocode AS varchar(20)) as ocode,
    CAST(dacode AS varchar(60)) as dacode,
    CAST(patrol_sysno AS varchar(60)) as patrol_sysno,
    CAST(patrol_lineid AS integer) as patrol_lineid,
    CAST(workprocess AS varchar(20)) as workprocess,
    CAST(badproject AS varchar(20)) as badproject,
    CAST(badproject1 AS varchar(20)) as badproject1,
    CAST(badproject2 AS varchar(20)) as badproject2,
    CAST(badproject3 AS varchar(20)) as badproject3,
    CAST(badproject4 AS varchar(20)) as badproject4,
    CAST(badproject5 AS varchar(20)) as badproject5,
    CAST(sampleqty_a AS numeric) as sampleqty_a,
    CAST(wqty_a AS numeric) as wqty_a,
    CAST(caq_waste_type_phid AS bigint) as caq_waste_type_phid,
    CAST(caq_mate_check_phid AS bigint) as caq_mate_check_phid
  FROM caq_proj_record
  UNION ALL
  SELECT 
    CAST(phid AS bigint) as phid,
    CAST(checkno AS varchar(60)) as checkno,
    CAST(wasteno AS varchar(8)) as wasteno,
    CAST(conclusion AS varchar(1)) as conclusion,
    CAST(sampleqty AS numeric) as sampleqty,
    CAST(wqty AS numeric) as wqty,
    CAST(stypeno AS varchar(30)) as stypeno,
    CAST(wbqty AS numeric) as wbqty,
    CAST(bbqty AS numeric) as bbqty,
    CAST(remarks AS varchar(255)) as remarks,
    CAST(def_int1 AS integer) as def_int1,
    CAST(def_int2 AS integer) as def_int2,
    CAST(def_str1 AS varchar(60)) as def_str1,
    CAST(def_str2 AS varchar(60)) as def_str2,
    CAST(def_str3 AS varchar(60)) as def_str3,
    CAST(def_num1 AS numeric) as def_num1,
    CAST(def_num2 AS numeric) as def_num2,
    CAST(tecrequest AS varchar(255)) as tecrequest,
    CAST(ocode AS varchar(20)) as ocode,
    CAST(dacode AS varchar(60)) as dacode,
    CAST(patrol_sysno AS varchar(60)) as patrol_sysno,
    CAST(patrol_lineid AS integer) as patrol_lineid,
    CAST(workprocess AS varchar(20)) as workprocess,
    CAST(badproject AS varchar(20)) as badproject,
    CAST(badproject1 AS varchar(20)) as badproject1,
    CAST(badproject2 AS varchar(20)) as badproject2,
    CAST(badproject3 AS varchar(20)) as badproject3,
    CAST(badproject4 AS varchar(20)) as badproject4,
    CAST(badproject5 AS varchar(20)) as badproject5,
    CAST(sampleqty_a AS numeric) as sampleqty_a,
    CAST(wqty_a AS numeric) as wqty_a,
    CAST(caq_waste_type_phid AS bigint) as caq_waste_type_phid,
    CAST(caq_mate_check_phid AS bigint) as caq_mate_check_phid
  FROM caq_proj_record_hi
);