CREATE OR REPLACE VIEW ng.uv_caq_ggcheck_rep AS
SELECT 
    phid,
    checkno,
    planno,
    checksort,
    checkpsn,
    gaugeno,
    deptno,
    checkdate,
    checkresult,
    fillinpsn,
    fillindate,
    isok,
    remarks,
    def_int1,
    def_int2,
    def_str1,
    def_str2,
    def_str3,
    def_str4,
    def_str5,
    def_num1,
    def_num2,
    def_num3,
    def_num4,
    def_num5,
    ocode,
    crecode,
    checkcomp,
    caq_gauge_phid,
    'N' AS is_history  -- 标记是否为历史数据
FROM ng.caq_ggcheck

UNION ALL

SELECT 
    phid,
    checkno,
    planno,
    checksort,
    checkpsn,
    gaugeno,
    deptno,
    checkdate,
    checkresult,
    fillinpsn,
    fillindate,
    isok,
    remarks,
    def_int1,
    def_int2,
    def_str1,
    def_str2,
    def_str3,
    def_str4,
    def_str5,
    def_num1,
    def_num2,
    def_num3,
    def_num4,
    def_num5,
    ocode,
    crecode,
    checkcomp,
    caq_gauge_phid,
    'Y' AS is_history  -- 标记是否为历史数据
FROM ng.caq_ggcheck_hi;